import {
  LayoutDashboard,
  Box,
  Cpu,
  ClipboardList,
  Settings,
  Bell,
  Mic,
  Search,
  User,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  Activity,
  AlertTriangle,
  Clock,
  CheckCircle2,
  MoreHorizontal,
  Thermometer,
  Zap,
  Plus,
  Trash2,
  Edit,
  FileText,
  Calendar,
  Wrench,
  Filter,
  X,
  Paperclip,
  Download,
  History,
  ListChecks,
  PlayCircle,
  StopCircle,
  PauseCircle,
  Camera,
  Sparkles,
  Package,
  Warehouse,
  TrendingDown,
  TrendingUp,
  AlertCircle,
  ShoppingCart,
  Printer,
  FileSpreadsheet,
  Droplets,
  Cog,
  Archive,
  Upload,
  CloudUpload,
  FileJson,
  CheckSquare,
  Square,
  Truck,
  ArrowRightLeft,
  PieChart,
  BarChart3,
  LineChart,
  Tag,
  MapPin,
  Database,
  Scale,
  Ruler,
  Gauge,
  Factory,
  Hash,
  Wind,
  Bot,
  Wifi,
  QrCode,
  Scan,
  GitMerge,
  Inbox,
  Smartphone,
  Image,
  Lock,
  LogOut,
  Grid3X3,
  RefreshCw,
  BarChart2,
  Crosshair,
  ArrowUpRight,
  ArrowDownRight,
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Asset: Box,
  AI: Cpu,
  WorkOrder: ClipboardList,
  Settings: Settings,
  Bell: Bell,
  Mic: Mic,
  Search: Search,
  User: User,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  ChevronDown: ChevronDown,
  Activity: Activity,
  Alert: AlertTriangle,
  AlertTriangle: AlertTriangle,
  Clock: Clock,
  Check: CheckCircle2,
  CheckCircle2: CheckCircle2,
  More: MoreHorizontal,
  Thermometer: Thermometer,
  Zap: Zap,
  Box: Box,
  Cpu: Cpu,
  ClipboardList: ClipboardList,
  Plus: Plus,
  Trash: Trash2,
  Edit: Edit,
  FileText: FileText,
  Calendar: Calendar,
  Wrench: Wrench,
  Filter: Filter,
  Close: X,
  Paperclip: Paperclip,
  Download: Download,
  History: History,
  ListChecks: ListChecks,
  Play: PlayCircle,
  Stop: StopCircle,
  Pause: PauseCircle,
  Camera: Camera,
  Sparkles: Sparkles,
  Package: Package,
  Warehouse: Warehouse,
  TrendingDown: TrendingDown,
  TrendingUp: TrendingUp,
  AlertCircle: AlertCircle,
  ShoppingCart: ShoppingCart,
  Printer: Printer,
  FileSpreadsheet: FileSpreadsheet,
  Droplets: Droplets,
  Cog: Cog,
  Archive: Archive,
  Upload: Upload,
  CloudUpload: CloudUpload,
  FileJson: FileJson,
  CheckSquare: CheckSquare,
  Square: Square,
  Truck: Truck,
  Transfer: ArrowRightLeft,
  PieChart: PieChart,
  BarChart: BarChart3,
  LineChart: LineChart,
  Tag: Tag,
  MapPin: MapPin,
  Database: Database,
  Scale: Scale,
  Ruler: Ruler,
  Gauge: Gauge,
  Factory: Factory,
  Hash: Hash,
  Wind: Wind,
  Bot: Bot,
  Wifi: Wifi,
  QrCode: QrCode,
  Scan: Scan,
  Hierarchy: GitMerge,
  Inbox: Inbox,
  Smartphone: Smartphone,
  Image: Image,
  Lock: Lock,
  LogOut: LogOut,
  Grid3X3: Grid3X3,
  RefreshCw: RefreshCw,
  BarChart2: BarChart2,
  Crosshair: Crosshair,
  ArrowUpRight: ArrowUpRight,
  ArrowDownRight: ArrowDownRight,
};
